language: c
compiler: gcc
matrix:
  include:
    - {}
    - env: arch=32
    - compiler: clang
    - env: nim_channel=devel
  allow_failures:
    - env: nim_channel=devel
  fast_finish: true
before_install:
  - nim_channel="${nim_channel-stable}"
  - |
    if [ "$nim_channel" = stable ]; then
      nim_branch="v$(curl https://nim-lang.org/channels/stable)"
    else
      nim_branch="$nim_channel"
    fi
install:
  - |
    if [ ! -x "nim-$nim_channel/bin/nim" ]; then
      git clone -b $nim_branch https://github.com/nim-lang/nim "nim-$nim_channel/"
      pushd "nim-$nim_channel"
      git clone --depth 1 https://github.com/nim-lang/csources csources/
      pushd csources
      sh build.sh
      popd
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
    else
      pushd "nim-$nim_channel"
      git fetch origin "$nim_branch"
      if ! git merge FETCH_HEAD | grep "Already up.to.date"; then
        bin/nim c koch
        ./koch boot -d:release
      fi
    fi
    popd
before_script:
  - |
    export PATH="nim-$nim_channel/bin${PATH:+:$PATH}"
    if [ "$arch" = 32 ]; then
        nim_flags="--cpu:i386 --passC:-m32 --passL:-m32"
    fi
script:
  - nim compile --cc:$CC $nim_flags --verbosity:0 --run test/test
cache:
  directories:
    - nim-stable
    - nim-devel
addons:
  apt:
    packages:
      - gcc-multilib
